<style type="text/css">
.developertoolbar {
	position: fixed;
	right: 0px;
	bottom: 0px;	
	width: 100%;
	text-align: left;
	width: 200px;
	background: #EEE;
	z-index: 10000;
	border: 1px solid black;
	padding: 5px;
}
.developertoolbar div.title a{background: none repeat scroll 0 0 #000; display:block; text-align:center; padding: 5px 0;}
.developertoolbar a {
	color: #FF822F;
	width: 200px;
	font-weight:bold;
	font-size:11px;
	text-decoration: none;
}

.developertoolbar a:hover {
	color: #A7C6DD;
}

.developertoolbar .bar_name {
	color: #D96708;
	font-size: 10px;
	font-weight:bold;
	cursor:pointer;
	padding-left: 3px;
}

.developertoolbar .hide_me {
	color: #D96708;
	font-size: 9px;
	font-weight:bold;	
	padding-right: 3px;	
}

.developertoolbar .seperate {
	width: 1px;
	border-right: 1px solid #415966;
}

.developertoolbar .disabled {
	color: #666;
}
</style>
<script type="text/javascript">
function toggle_developer_toolbar(){
	if (document.getElementById('bar_content').style.display == 'none') {
		document.getElementById('bar_content').style.display = "inline";
	} else {
		document.getElementById('bar_content').style.display = "none";
	}	
}
</script>